export default {
    DEFAULT_PAGINATION: 10,

    ADMIN_ID: 1,

    ROLE_ADMIN: 1,
    ROLE_TEACHER: 2,
    ROLE_STUDENT: 3,

    STAGE_CURRICULUM: 1,
    STAGE_EQUIVALENT: 2,
    STAGE_EXTRA_CURRICULUM: 3,
    STAGE_ONGOING: 4,
    STAGE_TO_ATTEND: 5,
    STAGE_CURRICULUM_EQUIVALENTS: 6,
}